### ISSUE TITLE
raise ConnectionError(err, request=request) requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

### ISSUE THREAD

**Issue by ljcohen** [dib-lab/osf-cli#106]
On MSU hpcc, the below error occurred. 

All project files seem to have downloaded, though... I will try again to see if I can replicate. Since I was on the head node, transfer might have been consuming too many resources so process may have been killed? Or something having to do with python conda env? Will login to `dev-intel14` node to see if that helps. 

Are there md5 hash of files on osf?

Or a way to see how many files total in the project? Says 118 files transferred below, but without counting them by hand on web interface, don't know how many total files in project. 

```
[ljcohen@gateway-00 TrunkRiver]$ osf -p 9bytm clone
118files [04:36,  2.78s/files]
Traceback (most recent call last):███████████████████████████████████████████████████████████| 8.29M/8.29M [00:00<00:00, 20.3Mbytes/s]
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 261, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/home/ljcohen/.conda/envs/dammit/bin/osf", line 11, in <module>
    sys.exit(main())
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/osfclient/__main__.py", line 104, in main
    exit_code = args.func(args)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/osfclient/cli.py", line 91, in wrapper
    return_value = f(cli_args)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/osfclient/cli.py", line 167, in clone
    file_.write_to(f)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/osfclient/models/file.py", line 53, in write_to
    response = self._get(self._download_url, stream=True)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/osfclient/models/core.py", line 23, in _get
    return self.session.get(url, *args, **kwargs)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/osfclient/models/session.py", line 43, in get
    response = super(OSFSession, self).get(url, *args, **kwargs)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/sessions.py", line 617, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/sessions.py", line 617, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/sessions.py", line 177, in resolve_redirects
    **adapter_kwargs
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/home/ljcohen/.conda/envs/dammit/lib/python3.5/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

**Comment by ljcohen** [comment]
Worked on `dev-intel14` with no error. 

This time with 191 files in project, so my previous attempt downloading 118 files was incorrect.  

```
[ljcohen@dev-intel14 MicDiv]$ osf -p 9bytm clone
191files [14:58, 51.92s/files]
```

**Comment by betatim** [comment]
From the error message it looks like osf.io just hung up on you. Hard to know why really.
