### ISSUE TITLE
Gracefully handle 404s

### ISSUE THREAD

**Issue by sloria** [dib-lab/osf-cli#122]
## Steps

Pass a GUID that isn't associated with an OSF project

```
osf -p notaproject clone
```

## Expected

A human-friendly error message, something like: `Could not find project "notaproject". Please check the -p/--project argument`

## Actual

Unhandled error message:

```
Traceback (most recent call last):
  File "/Users/sloria/miniconda/envs/osf-cli/bin/osf", line 11, in <module>
    load_entry_point('osfclient', 'console_scripts', 'osf')()
  File "/Users/sloria/projects/cos-projects/osf-cli/osfclient/__main__.py", line 104, in main
    exit_code = args.func(args)
  File "/Users/sloria/projects/cos-projects/osf-cli/osfclient/cli.py", line 91, in wrapper
    return_value = f(cli_args)
  File "/Users/sloria/projects/cos-projects/osf-cli/osfclient/cli.py", line 148, in clone
    project = osf.project(args.project)
  File "/Users/sloria/projects/cos-projects/osf-cli/osfclient/api.py", line 24, in project
    return Project(self._json(self._get(url), 200), self.session)
  File "/Users/sloria/projects/cos-projects/osf-cli/osfclient/models/core.py", line 60, in _json
    status_code))
RuntimeError: Response has status code 404 not (200,)
```

**Comment by betatim** [comment]
Related [comment](https://github.com/dib-lab/osf-cli/issues/107#issuecomment-328460108) on better error messages.
