### ISSUE TITLE
need to test with institutional logins

### ISSUE THREAD

**Issue by nkmeyers** [dib-lab/osf-cli#130]
M Suhovecky at ND reports OSFCLI doesn't work as expected w/institutional logins - need to explore and test for this.

**Comment by BRosenblatt** [comment]
@nkmeyers, can you provide more detail here? What's the expected behavior and what's the actual behavior?

**Comment by pankajkgupta** [comment]
Hi, I have institutional login at OSF and wondering how to use the institutional login with osfclient as there is no username password associated at osf website.

**Comment by felliott** [comment]
Hey @pankajkgupta,

We're working on adding Personal Access Token support currently.  You can track the progress of the ticket at #163.  This is our highest priority for the next release.

Cheers,
Fitz

**Comment by felliott** [comment]
Hey @pankajkgupta,

I've just merged #163 into the `develop` branch.  Would you mind testing it?  It should go out in the next release.

Thank you!

Cheers,
@felliott

**Comment by pankajkgupta** [comment]
Hi, sorry @felliott  for the delay in testing.

I installed the develop branch osfclient and-

- created `.osfcli.config` by running `osf init`
- edit `osfcli.config` to add `token = <personal token>`
- ran `osf ls` to see list of files in my personal osf project
`osf ls` throws following error:
`Traceback (most recent call last):
  File "/home/pankaj/.virtualenvs/py37cv4/bin/osf", line 11, in <module>
    load_entry_point('osfclient', 'console_scripts', 'osf')()
  File "/media/pankaj/Seagate Expansion Drive/codebase/osfclient/osfclient/__main__.py", line 113, in main
    exit_code = args.func(args)
  File "/media/pankaj/Seagate Expansion Drive/codebase/osfclient/osfclient/cli.py", line 97, in wrapper
    return_value = f(cli_args)
  File "/media/pankaj/Seagate Expansion Drive/codebase/osfclient/osfclient/cli.py", line 239, in list_
    project = osf.project(args.project)
  File "/media/pankaj/Seagate Expansion Drive/codebase/osfclient/osfclient/api.py", line 31, in project
    type_ = self.guid(project_id)
  File "/media/pankaj/Seagate Expansion Drive/codebase/osfclient/osfclient/api.py", line 39, in guid
    return self._json(self._get(self._build_url('guids', guid)), 200)['data']['type']
  File "/media/pankaj/Seagate Expansion Drive/codebase/osfclient/osfclient/models/core.py", line 63, in _json
    status_code))
RuntimeError: Response has status code 404 not (200,)
`
