### ISSUE TITLE
syntax error with python 2.7.12

### ISSUE THREAD

**Issue by ctb** [dib-lab/osf-cli#46]
is this a py3 issue?

```
# after running sudo pip install -e .
% osf
Traceback (most recent call last):
  File "/usr/local/bin/osf", line 9, in <module>
    load_entry_point('osfclient', 'console_scripts', 'osf')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/titus/osf-cli/osfclient/__init__.py", line 2, in <module>
    from .api import OSF
  File "/home/titus/osf-cli/osfclient/api.py", line 1, in <module>
    from .models import OSFCore
  File "/home/titus/osf-cli/osfclient/models/__init__.py", line 6, in <module>
    from .core import OSFCore
  File "/home/titus/osf-cli/osfclient/models/core.py", line 31
    def _get_attribute(self, json, *keys, default=None):
                                                ^
SyntaxError: invalid syntax
```

**Comment by betatim** [comment]
Yes, this is only valid python not legacy python :)

**Comment by betatim** [comment]
(but not hard to fix, so we should do that)

**Comment by luizirber** [comment]
Good presentation about this feature (keyword only arguments): http://www.asmeurer.com/python3-presentation/slides.html#9
